- src/main/java/hsge/hsgeback/entity/Chatroom.java
- src/main/java/hsge/hsgeback/entity/Match.java
- src/main/java/hsge/hsgeback/entity/Message.java
- src/main/java/hsge/hsgeback/entity/Participant.java
- src/main/java/hsge/hsgeback/entity/Pet.java
- src/main/java/hsge/hsgeback/entity/Report.java
- src/main/java/hsge/hsgeback/entity/User.java
> refactor: 엔티티 개선 #1

- src/main/java/hsge/hsgeback/config/SecurityConfig.java
- src/main/java/hsge/hsgeback/config/WebClientConfig.java
- src/main/java/hsge/hsgeback/config/WebConfig.java
- src/main/java/hsge/hsgeback/dto/kakao/KakaoUser.java
- src/main/java/hsge/hsgeback/dto/kakao/TokenInfo.java
- src/main/java/hsge/hsgeback/dto/kakao/UserInfo.java
- src/main/java/hsge/hsgeback/dto/response/BaseResponseDto.java
- src/main/java/hsge/hsgeback/exception/AccessTokenException.java
- src/main/java/hsge/hsgeback/exception/BadWebClientRequestException.java
- src/main/java/hsge/hsgeback/exception/advice/ErrorResult.java
- src/main/java/hsge/hsgeback/exception/advice/ExceptionControllerAdvice.java
- src/main/java/hsge/hsgeback/security/KakaoUserDetailService.java
- src/main/java/hsge/hsgeback/security/filter/LoginFilter.java
- src/main/java/hsge/hsgeback/security/filter/TokenCheckFilter.java
- src/main/java/hsge/hsgeback/security/handler/LoginFailureHandler.java
- src/main/java/hsge/hsgeback/security/handler/LoginSuccessHandler.java
- src/main/java/hsge/hsgeback/util/JWTUtil.java
인증된 액세스토큰으로 보내면 JWT 토큰 전송해주고,
안되면 회원가입할 수 있도록 처리
> feat: 액세스토큰 기반으로 로그인 기능 구현 #2

- src/main/java/hsge/hsgeback/DataInit.java
- src/main/java/hsge/hsgeback/entity/Pet.java
> chore: dummy data 추가

- src/main/java/hsge/hsgeback/entity/User.java
> refactor: User 엔티티 수정 #1

- src/main/java/hsge/hsgeback/controller/UserController.java
- src/main/java/hsge/hsgeback/dto/request/MypageDto.java
- src/main/java/hsge/hsgeback/service/UserService.java
https://github.com/team-HSGE/hsge-back/issues/19#issuecomment-1338831166
- 회원 정보 조회
- 회원 정보 수정
- 유저 반경 변경
- 유저 위도, 경도 변경
> feat: Dto, 컨트롤러, 서비스 생성 #19

- src/main/java/hsge/hsgeback/config/SecurityConfig.java
- src/main/java/hsge/hsgeback/controller/AuthController.java
- src/main/java/hsge/hsgeback/controller/PetController.java
- src/main/java/hsge/hsgeback/controller/UserController.java
- src/main/java/hsge/hsgeback/dto/request/UserPetDto.java
- src/main/java/hsge/hsgeback/exception/TokenException.java
- src/main/java/hsge/hsgeback/security/filter/ExceptionHandlerFilter.java
- src/main/java/hsge/hsgeback/security/filter/LoginFilter.java
- src/main/java/hsge/hsgeback/service/AuthService.java
- src/main/java/hsge/hsgeback/service/PetService.java
- src/main/java/hsge/hsgeback/service/UserService.java
https://github.com/team-HSGE/hsge-back/issues/19#issuecomment-1340513878
> #19 로그인 시 유효하지 않은 Access Token 오류 메시지 & 회원 탈퇴 기능 생성

- src/main/java/hsge/hsgeback/config/SecurityConfig.java
- src/main/java/hsge/hsgeback/controller/AuthController.java
- src/main/java/hsge/hsgeback/controller/PetController.java
- src/main/java/hsge/hsgeback/controller/UserController.java
- src/main/java/hsge/hsgeback/dto/request/PutDto.java
- src/main/java/hsge/hsgeback/dto/request/UserPetDto.java
- src/main/java/hsge/hsgeback/dto/response/PetInfoResponseDto.java
- src/main/java/hsge/hsgeback/entity/Pet.java
- src/main/java/hsge/hsgeback/exception/NotOwnerException.java
- src/main/java/hsge/hsgeback/exception/TokenException.java
- src/main/java/hsge/hsgeback/exception/advice/ExceptionControllerAdvice.java
- src/main/java/hsge/hsgeback/security/filter/ExceptionHandlerFilter.java
- src/main/java/hsge/hsgeback/security/filter/LoginFilter.java
- src/main/java/hsge/hsgeback/service/AuthService.java
- src/main/java/hsge/hsgeback/service/PetService.java
- src/main/java/hsge/hsgeback/service/UserService.java
https://github.com/team-HSGE/hsge-back/issues/11#issuecomment-1338961107 - 특정 반려견 조회 서비스와 컨트롤러 생성
https://github.com/team-HSGE/hsge-back/issues/11#issuecomment-1339491617 - 본인 반려견 리스트 조회 컨트롤러 및 서비스 생성
https://github.com/team-HSGE/hsge-back/issues/11#issuecomment-1339555450 - 반려견 삭제 컨트롤러 및 서비스 생성
https://github.com/team-HSGE/hsge-back/issues/11#issuecomment-1339567258 - 본인 반려견 추가 기능 추가
https://github.com/team-HSGE/hsge-back/issues/11#issuecomment-1340266720 - 본인 반려견 수정 서비스 컨트롤러 생성
https://github.com/team-HSGE/hsge-back/issues/11#issuecomment-1340507433 - updatePet 메서드로 예외처리
> feat: Dto 생성, 필드 수정 및 특정유저반려견 서비스, 컨트롤러 개발 #11

- src/main/java/hsge/hsgeback/controller/UserController.java
- src/main/java/hsge/hsgeback/dto/request/SignupDto.java
- src/main/java/hsge/hsgeback/entity/User.java
- src/main/java/hsge/hsgeback/service/UserService.java
https://github.com/team-HSGE/hsge-back/issues/27#issuecomment-1343768350
> feat: 유저 신고 기능 생성 #27

- src/main/java/hsge/hsgeback/dto/request/ReportDto.java
https://github.com/team-HSGE/hsge-back/issues/27#issuecomment-1343868606
> feat: ReportDto 생성 #27

- .gitignore
- build.gradle
- src/main/java/hsge/hsgeback/config/FirebaseConfig.java
- src/main/java/hsge/hsgeback/config/QueryDslConfig.java
- src/main/java/hsge/hsgeback/constant/PushNotification.java
- src/main/java/hsge/hsgeback/controller/MatchController.java
- src/main/java/hsge/hsgeback/dto/match/UserPetMatchDto.java
- src/main/java/hsge/hsgeback/dto/request/UserPetInterestDto.java
- src/main/java/hsge/hsgeback/entity/Match.java
- src/main/java/hsge/hsgeback/entity/User.java
- src/main/java/hsge/hsgeback/exception/ResourceNotFoundException.java
- src/main/java/hsge/hsgeback/exception/advice/ErrorResult.java
- src/main/java/hsge/hsgeback/exception/advice/ExceptionControllerAdvice.java
- src/main/java/hsge/hsgeback/repository/PetCustomRepository.java
- src/main/java/hsge/hsgeback/repository/UserCustomRepository.java
- src/main/java/hsge/hsgeback/service/FcmService.java
- src/main/java/hsge/hsgeback/service/MatchService.java
- src/main/java/hsge/hsgeback/util/MessageUtil.java
- src/test/java/hsge/hsgeback/util/MessageUtilTest.java
https://github.com/team-HSGE/hsge-back/issues/28#issuecomment-1350698060
> #28 매칭 기능(좋아요, 싫어요 저장), FCM 푸시 알림

- src/main/java/hsge/hsgeback/controller/PetController.java
- src/main/java/hsge/hsgeback/service/PetService.java
https://github.com/team-HSGE/hsge-back/issues/11#issuecomment-1358724603
> refactor: 본인 강아지만 삭제할 수 있게 수정 #11

- src/main/java/hsge/hsgeback/controller/AuthController.java
- src/main/java/hsge/hsgeback/controller/ChatController.java
- src/main/java/hsge/hsgeback/controller/MatchController.java
- src/main/java/hsge/hsgeback/dto/chat/ChatSimpleDto.java
- src/main/java/hsge/hsgeback/dto/firebase/FcmTokenDto.java
- src/main/java/hsge/hsgeback/dto/match/UserPetMatchDto.java
- src/main/java/hsge/hsgeback/entity/Chatroom.java
- src/main/java/hsge/hsgeback/entity/Message.java
- src/main/java/hsge/hsgeback/entity/User.java
- src/main/java/hsge/hsgeback/repository/ChatroomCustomRepository.java
- src/main/java/hsge/hsgeback/repository/UserCustomRepository.java
- src/main/java/hsge/hsgeback/service/AuthService.java
- src/main/java/hsge/hsgeback/service/ChatService.java
- src/main/java/hsge/hsgeback/service/FcmService.java
- src/main/java/hsge/hsgeback/service/MatchService.java
https://github.com/team-HSGE/hsge-back/issues/28#issuecomment-1358753253
> #28 FCM 토큰 저장/삭제, 채팅 목록 가져오기

- src/main/java/hsge/hsgeback/dto/request/SignupDto.java
- src/main/java/hsge/hsgeback/entity/User.java
- src/main/java/hsge/hsgeback/service/UserService.java
- 유저 엔티티에 isValid 필드값 추가
- 신고 받은 횟수인 reportCount 필드 값 추가
- signupDto fcm 값 받을 필드값 추가 및 수정
- 신고 관련 로직 추가
https://github.com/team-HSGE/hsge-back/issues/19#issuecomment-1360598433
> refactor: 유저 신고 관련 기능 수정, 회원가입 시 fcm 값 받는 기능 수정 #19

- src/main/java/hsge/hsgeback/repository/ReportRepository.java
https://github.com/team-HSGE/hsge-back/issues/19#issuecomment-1360630333
> refactor: ReportRepository에 jpql 추가 #19

- src/main/java/hsge/hsgeback/dto/request/SignupDto.java
- src/main/java/hsge/hsgeback/dto/response/AgeDto.java
- src/main/java/hsge/hsgeback/dto/response/BreedDto.java
- src/main/java/hsge/hsgeback/dto/response/PetInfoResponseDto.java
- src/main/java/hsge/hsgeback/dto/response/PetResponseDto.java
- src/main/java/hsge/hsgeback/entity/User.java
- src/main/java/hsge/hsgeback/repository/UserRepository.java
- src/main/java/hsge/hsgeback/service/AuthService.java
- src/main/java/hsge/hsgeback/service/PetService.java
- src/main/java/hsge/hsgeback/service/UserService.java
- longtitude -> longitude 수정
https://github.com/team-HSGE/hsge-back/issues/11#issuecomment-1361016945
> refactor: PetService 로직 리팩토링 #11

- src/main/java/hsge/hsgeback/config/SecurityConfig.java
- src/main/java/hsge/hsgeback/security/filter/ReportCheckFilter.java
일정 횟수를 신고받은 유저는 필터를 통해 에러 메시지 받도록 처리
https://github.com/team-HSGE/hsge-back/issues/43#issue-1510221517
> feat: 신고 유저 이용 못하게 밴 처리 #43

- src/main/java/hsge/hsgeback/HsgeBackApplication.java
- src/main/java/hsge/hsgeback/constant/FcmPushId.java
- src/main/java/hsge/hsgeback/controller/MatchController.java
- src/main/java/hsge/hsgeback/dto/common/BasicResponse.java
- src/main/java/hsge/hsgeback/entity/Message.java
- src/main/java/hsge/hsgeback/event/match/MatchedEvent.java
- src/main/java/hsge/hsgeback/event/match/MatchedEventHandler.java
- src/main/java/hsge/hsgeback/event/match/MatchedEventPublisher.java
- src/main/java/hsge/hsgeback/exception/ResourceDuplicateException.java
- src/main/java/hsge/hsgeback/exception/advice/ErrorResult.java
- src/main/java/hsge/hsgeback/exception/advice/ExceptionControllerAdvice.java
- src/main/java/hsge/hsgeback/repository/ChatroomRepository.java
- src/main/java/hsge/hsgeback/repository/MatchRepository.java
- src/main/java/hsge/hsgeback/repository/chat/ChatroomRepository.java
- src/main/java/hsge/hsgeback/repository/chat/ChatroomRepositoryCustom.java
- src/main/java/hsge/hsgeback/repository/chat/ChatroomRepositoryImpl.java
- src/main/java/hsge/hsgeback/repository/chat/MessageRepository.java
- src/main/java/hsge/hsgeback/repository/match/MatchRepository.java
- src/main/java/hsge/hsgeback/repository/match/MatchRepositoryCustom.java
- src/main/java/hsge/hsgeback/repository/match/MatchRepositoryImpl.java
- src/main/java/hsge/hsgeback/repository/user/UserRepository.java
- src/main/java/hsge/hsgeback/repository/user/UserRepositoryCustom.java
- src/main/java/hsge/hsgeback/repository/user/UserRepositoryImpl.java
- src/main/java/hsge/hsgeback/security/KakaoUserDetailService.java
- src/main/java/hsge/hsgeback/service/AuthService.java
- src/main/java/hsge/hsgeback/service/ChatService.java
- src/main/java/hsge/hsgeback/service/FcmService.java
- src/main/java/hsge/hsgeback/service/MatchService.java
- src/main/java/hsge/hsgeback/service/PetService.java
- src/main/java/hsge/hsgeback/service/UserService.java
FCM 관련 https://github.com/team-HSGE/hsge-back/issues/41#issuecomment-1366376059
매칭시 채팅방 생성 관련 https://github.com/team-HSGE/hsge-back/issues/42#issuecomment-1366379263
> feat: fcm 푸시 알림 이벤트 처리, 레포지토리 구조 변경, 매칭 예외 처리 추가 #41

- build.gradle
- src/main/java/hsge/hsgeback/config/RedisConfig.java
- src/main/java/hsge/hsgeback/config/SecurityConfig.java
- src/main/java/hsge/hsgeback/controller/UserController.java
- src/main/java/hsge/hsgeback/dto/redis/LocationDto.java
- src/main/java/hsge/hsgeback/dto/redis/WalkDto.java
- src/main/java/hsge/hsgeback/service/UserService.java
- src/main/resources/application-dev.yml
- src/main/resources/application-prod.yml
- src/main/resources/application.yml
https://github.com/team-HSGE/hsge-back/issues/46#issuecomment-1366386761
https://github.com/team-HSGE/hsge-back/issues/46#issuecomment-1366391964
> feat: redis 사용하여 손흔들기 시 주기적으로 위경도 받는 기능  #46

- src/main/java/hsge/hsgeback/DataInit.java
- src/main/java/hsge/hsgeback/controller/ChatController.java
- src/main/java/hsge/hsgeback/controller/MessageController.java
- src/main/java/hsge/hsgeback/event/match/MatchedEvent.java
- src/main/java/hsge/hsgeback/repository/chat/ChatroomRepositoryImpl.java
- src/main/java/hsge/hsgeback/service/ChatService.java
> refactor: 웹소켓 연결 #47

- src/main/java/hsge/hsgeback/dto/chat/ChatSimpleDto.java
- src/main/java/hsge/hsgeback/repository/chat/ChatroomRepositoryCustom.java
- src/main/java/hsge/hsgeback/repository/chat/ChatroomRepositoryImpl.java
- src/main/java/hsge/hsgeback/service/ChatService.java
https://github.com/team-HSGE/hsge-back/issues/54#issue-1513452130
> fix: 양쪽에서 매칭시 채팅 목록에 노출, 메시지 보낸 날짜 추가 #54

- src/main/java/hsge/hsgeback/DataInit.java
- src/main/java/hsge/hsgeback/HsgeBackApplication.java
- src/main/java/hsge/hsgeback/controller/ChatController.java
- src/main/java/hsge/hsgeback/entity/Chatroom.java
- src/main/java/hsge/hsgeback/repository/chat/ChatroomRepositoryImpl.java
- src/main/java/hsge/hsgeback/service/ChatService.java
> feat: 채팅 활성화 API 개발 #47

- src/main/java/hsge/hsgeback/config/RedisConfig.java
- src/main/java/hsge/hsgeback/controller/UserController.java
- src/main/java/hsge/hsgeback/dto/redis/Location.java
- src/main/java/hsge/hsgeback/dto/redis/LocationDto.java
- src/main/java/hsge/hsgeback/dto/redis/ResponseDto.java
- src/main/java/hsge/hsgeback/repository/user/UserRepository.java
- src/main/java/hsge/hsgeback/service/UserService.java
- 컨트롤러, 서비스 코드 추가
- 필요한 DTO 생성
> feat: 레디스 사용해서 탐색기능 사용하는 사람들만 정보를 받을 수 있는 기능    #46

- src/main/java/hsge/hsgeback/controller/UserController.java
- src/main/java/hsge/hsgeback/dto/redis/NameDto.java
- src/main/java/hsge/hsgeback/service/UserService.java
https://github.com/team-HSGE/hsge-back/issues/46#issuecomment-1370538465
> chore: 응답값 이름으로 반환    #46

- src/main/java/hsge/hsgeback/constant/PushNotification.java
- src/main/java/hsge/hsgeback/controller/MessageController.java
- src/main/java/hsge/hsgeback/dto/chat/MessageSentEventDto.java
- src/main/java/hsge/hsgeback/dto/request/MessageRequestDto.java
- src/main/java/hsge/hsgeback/event/chat/MessageSentEvent.java
- src/main/java/hsge/hsgeback/event/chat/MessageSentEventHandler.java
- src/main/java/hsge/hsgeback/event/chat/MessageSentEventPublisher.java
- src/main/java/hsge/hsgeback/event/match/MatchEventHandler.java
- src/main/java/hsge/hsgeback/service/FcmService.java
- src/main/java/hsge/hsgeback/service/WaveService.java
- src/main/java/hsge/hsgeback/util/MessageUtil.java
https://github.com/team-HSGE/hsge-back/issues/41#issuecomment-1371851811
> feat: 채팅 메시지 푸시 알림 추가 #41
